pets_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :owners
  resources :pets
  get "owners/:id/pets", to: "owners#pets_by_owner"
end

pets_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pets_app/app/models/owner.rb
class Owner < ApplicationRecord
  has_many :pets
end

pets_app/app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner
end

pets_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

pets_app/app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  # get all owners
  def index
    @owners = Owner.all
    # render json: owners
  end

  def show
    @owners = Owner.find(params[:id])
  end

end
  # get method
  # def show
  #   owner = Owner.find(params[:id])
  #   # render json: owner
  # end

  # # post method
  # def create
  #   p "in create. owner_params:", owner_params
  #   owner = Owner.create!(owner_params)
  #   # render json: owner
  # end

  # # put method
  # def update
  #   owner = Owner.find(params[:id])
  #   owner.update!(owner_params)
  #   # render json: owner
  # end

  # # delete method
  # def destroy
  #   owner = Owner.find(params[:id])
  #   owner.destroy!
  #   render plain: "owner DELETED!"
  # end

  # # allows us to get/view all of the pets associated 
  # # by owner id at this route 'localhost:3000/owners/:id/pets'
  # def pets_by_owner
  #   owner = Owner.find(params[:id])
  #   # render json: owner.pets
  # end

  # private

  # # defining the variable owner_params
  # def owner_params
  #   params.require(:owner).permit(:owner_name)
  # end

# end

pets_app/app/controllers/pets_controller.rb
class PetsController < ApplicationController

  # get all pets
  def index
    @pets = Pet.all
  end

  # get method for individual pet
  def show
    @pet = Pet.find(params[:id])
  end

  def new 
    @pet = Pet.new
  end

  # post method
  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to @pet
    else
      render :action => :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  # put method
  def update 
    @pet = Pet.find(params[:id])

    if @pet.update(pet_params)
      redirect_to @pet
    else
      render :action => :edit
      # render 'edit'
    end
  end

  # delete method
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_url
  end

  private
  # defining the variable pet_params...
  def pet_params
    params.require(:pet).permit(:pet_name, :pet_specie, :pet_image, :owner_id)
  end

end

pets_app/app/views/owners/index.html.erb
<h3>Pet Owners!</h3>

<% @owners.each do |owner| %>
  <p>Name: <%= owner[:owner_name] %></p>

  <% end %>

pets_app/app/views/owners/show.html.erb
<h1>Hello from the owners/show page!</h1>

pets_app/app/views/pets/_form.html.erb
<%= form_for @pet do |form| %>
  Name: <%= form.text_field :pet_name %>
  Specie: <%= form.text_field :pet_specie %>
  Image: <%= form.text_field :pet_image %>
  Owner Id: <%= form.text_field :owner_id %>
  
  <%= form.submit %>
<% end %>

pets_app/app/views/pets/edit.html.erb
<%= link_to 'Back to the list of pets!', pets_path %>

<h3>Let's Edit this Pet!</h3>

<%= render :partial => 'form' %>

pets_app/app/views/pets/index.html.erb
<div>
  <h1>All of the Pets!</h1>

<!-- <a href="/pets/new">Add a New Pet!</a> -->
  <h3><%= link_to 'Add a New Pet!', new_pet_path %></h3>

<!-- this iterates through the list of pets  -->
    <% @pets.each do |pet| %>
  <ul>
<!-- this displays each of the pet names, along with their id paths (1, 2, 3) -->
    <%= link_to pet[:pet_name], pet_path(pet) %>
  </ul>
  
  <br />

  <%= button_to 'Delete', pet, :method => 'delete', data: {confirm: 'Are you sure you want to delete this pet?'} %>

  <% end %>

</div>

pets_app/app/views/pets/new.html.erb
<%= link_to 'Back to the list of pets!', pets_path %>
<h1>Let's add a new pet!</h1>
<%= render :partial => 'form' %>

pets_app/app/views/pets/show.html.erb
<h1><%= @pet.pet_name %>'s Page!</h1>

<%= link_to 'Back to the list of pets!', pets_path%>
<br />
<br />
<%= link_to 'Edit this pet!', edit_pet_path%>


<p>Name: <%= @pet.pet_name %> </p>
<p>Pet Specie: <%= @pet.pet_specie %> </p>
<!-- <p>Owner : <%= link_to 'John', owners_path%> </p> -->
<p><%= link_to 'Owners', owners_path %></p>
<img src="<%= @pet.pet_image %>" />